const initialValue: Record<string, Record<string, string>> = {
  form1: { task: 'Eat some food', checked: 'yeah' },
  form2: { task: 'Eat some food', checked: 'yeah' },
  form3: { task: 'Eat some food', checked: 'yeah' },
  form4: { task: 'Eat some food', checked: 'yeah' },
  form5: { task: 'Eat some food', checked: 'yeah' },
  form6: { task: 'Eat some food', checked: 'yeah' },
  form7: { task: 'Eat some food', checked: 'yeah' },
  form8: { task: 'Eat some food', checked: 'yeah' },
  form12: { task: 'Eat some food', checked: 'yeah' },
  form22: { task: 'Eat some food', checked: 'yeah' },
  form32: { task: 'Eat some food', checked: 'yeah' },
  form42: { task: 'Eat some food', checked: 'yeah' },
  form52: { task: 'Eat some food', checked: 'yeah' },
  form62: { task: 'Eat some food', checked: 'yeah' },
  form72: { task: 'Eat some food', checked: 'yeah' },
  form82: { task: 'Eat some food', checked: 'yeah' },
  form14: { task: 'Eat some food', checked: 'yeah' },
  form24: { task: 'Eat some food', checked: 'yeah' },
  form34: { task: 'Eat some food', checked: 'yeah' },
  form44: { task: 'Eat some food', checked: 'yeah' },
  form54: { task: 'Eat some food', checked: 'yeah' },
  form64: { task: 'Eat some food', checked: 'yeah' },
  form74: { task: 'Eat some food', checked: 'yeah' },
  form84: { task: 'Eat some food', checked: 'yeah' },
  form15: { task: 'Eat some food', checked: 'yeah' },
  form25: { task: 'Eat some food', checked: 'yeah' },
  form35: { task: 'Eat some food', checked: 'yeah' },
  form45: { task: 'Eat some food', checked: 'yeah' },
  form55: { task: 'Eat some food', checked: 'yeah' },
  form65: { task: 'Eat some food', checked: 'yeah' },
  form75: { task: 'Eat some food', checked: 'yeah' },
  form85: { task: 'Eat some food', checked: 'yeah' },
}

export default initialValue
