name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: './dist/**/*.{js,mjs}'
